"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const cp=require("node:child_process");
const net=require("node:net");
const root=path.resolve(__dirname,"..");
const findChrome=()=>["google-chrome","google-chrome-stable","chromium","chromium-browser"].map(name=>cp.spawnSync("bash",["-lc",`command -v ${name}`],{encoding:"utf8"})).find(r=>r.status===0&&r.stdout.trim())?.stdout.trim()||"";
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function freePort(){return new Promise((resolve,reject)=>{const server=net.createServer();server.once("error",reject);server.listen(0,"127.0.0.1",()=>{const port=server.address().port;server.close(()=>resolve(port));});});}
async function connectChrome(chrome){
    const port=await freePort(),profile=fs.mkdtempSync(path.join(require("node:os").tmpdir(),"backpack-runtime-"));
    const child=cp.spawn(chrome,["--headless=new","--no-sandbox","--disable-gpu","--disable-dev-shm-usage","--allow-file-access-from-files","--remote-debugging-address=127.0.0.1",`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,"about:blank"],{stdio:"ignore"});
    let target;for(let i=0;i<100&&!target;i++){try{target=(await (await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find(row=>row.type==="page"&&row.webSocketDebuggerUrl);}catch(_){}if(!target)await sleep(50);}
    assert.ok(target,"Chrome DevTools target unavailable");
    const socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener("open",resolve,{once:true});socket.addEventListener("error",reject,{once:true});});
    let id=0;const pending=new Map();socket.addEventListener("message",event=>{const message=JSON.parse(String(event.data));if(message.id&&pending.has(message.id)){const promise=pending.get(message.id);pending.delete(message.id);message.error?promise.reject(new Error(message.error.message)):promise.resolve(message.result);}});
    const send=(method,params={})=>new Promise((resolve,reject)=>{const next=++id;pending.set(next,{resolve,reject});socket.send(JSON.stringify({id:next,method,params}));});
    return {send,close:()=>{socket.close();child.kill("SIGKILL");fs.rmSync(profile,{recursive:true,force:true});}};
}

const chrome=findChrome();
if(!chrome){if(process.env.CI)throw new Error("Backpack Browser Visual QA requires Chrome/Chromium in CI");console.log("Backpack Browser Visual QA skipped: Chrome/Chromium not available");process.exit(0);}

const manifest=JSON.parse(fs.readFileSync(path.join(root,"build/asset-manifest.json"),"utf8"));
const stylePaths=[...(manifest.critical?.styles||[]),...Object.values(manifest.featureManifest?.bundles||{}).flatMap(bundle=>bundle.styles||[])].filter((file,index,all)=>file&&all.indexOf(file)===index);
assert.ok(stylePaths.some(file=>file.includes("gameplay-core")),"fixture must load the production gameplay CSS bundle");
const equipmentProgressionSource=fs.readFileSync(path.join(root,"js/equipment-progression.js"),"utf8");
const functionalFixesSource=fs.readFileSync(path.join(root,"js/58-v173.63-functional-fixes.js"),"utf8");
const injectedRarityMatch=equipmentProgressionSource.match(/\.v17346-rarity-white[\s\S]*?@keyframes v17360FourSymbolRarityBreath\{[\s\S]*?\}/);
assert.ok(injectedRarityMatch,"fixture must source v17346 rarity CSS from equipment-progression.js");
const injectedMaterialMatch=functionalFixesSource.match(/#game-stage \.v169-material-art:not\(\.inventory-backpack-rarity-neutral\)[\s\S]*?#game-stage #homeFeatureModal\.v141-synthesis-modal/);
assert.ok(injectedMaterialMatch,"fixture must source material rarity CSS from js/58 runtime injection");
const styles=stylePaths.map(file=>`<link rel="stylesheet" href="${file}">`).join("")+`<style id="equipment-progression-style">${injectedRarityMatch[0]}</style><style id="functional-material-style">${injectedMaterialMatch[0]}</style>`;
const equipmentArt='<span class="v169-item-art v169-equipment-art v169-rarity-orange v17346-rarity-orange inventory-backpack-rarity-neutral"><img alt="裝備" src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'64\' height=\'64\'%3E%3Crect width=\'64\' height=\'64\' fill=\'%23c88f30\'/%3E%3C/svg%3E"></span>';
const materialArt='<span class="v169-item-art v169-material-art v169-rarity-blue inventory-backpack-rarity-neutral"><img alt="材料" src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'64\' height=\'64\'%3E%3Crect width=\'64\' height=\'64\' fill=\'%2342a5ff\'/%3E%3C/svg%3E"></span>';

                                                 const rarities=["white","blue","purple","orange","red","myriad"];
const slots=Array.from({length:24},(_,index)=>`<button class="inventory-item-classic rarity-${rarities[index%rarities.length]}${index===3?" is-selected":""}"><span class="inventory-icon">${index%2?materialArt:equipmentArt}</span><b class="inventory-count">${index+1}</b></button>`).join("");
const equipment=Array.from({length:6},(_,index)=>`<div class="inventory-equipment-cell"><span class="inventory-equipment-slot-label">部位${index+1}</span><div class="inventory-equipment-slot">${index===0?equipmentArt:index+1}</div></div>`).join("");
const fixture=path.join(root,".backpack-visual-qa.html");
const html=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${styles}<style>html,body{margin:0;width:100%;min-height:100%;overflow-x:hidden;background:#050708}#game-stage,#game-stage>#app,#game-stage #inventoryPage{width:100%!important;min-width:0!important;max-width:100vw!important;overflow-x:visible}#game-stage{min-height:100vh;overflow:visible}.inventory-portrait-frame{min-height:0!important}</style></head><body><main id="game-stage"><div id="app"><div id="inventoryPage"><div class="inventory-classic-shell"><header class="inventory-header"><div class="inventory-title-plate"><span class="inventory-title-plate-kicker">INVENTORY</span><h2>背包</h2></div><button class="map-inventory-overlay-close">關閉</button></header><div class="inventory-character-switch"><button class="inventory-character-arrow">‹</button><span class="inventory-character-name">角色一 <small>Lv.40</small></span><button class="inventory-character-arrow">›</button></div><div class="inventory-character-stage"><div class="inventory-portrait-frame"><span>角色立繪</span></div><div class="inventory-equipment-grid">${equipment}</div></div><div class="inventory-right-panel"><div class="inventory-category-tabs"><div class="inventory-category-tab active">裝備</div><div class="inventory-category-tab">物品</div><div class="inventory-category-tab">材料</div><div class="inventory-category-tab">功能</div></div><div id="inventoryGridScroll" class="inventory-grid-scroll"><div id="inventoryGrid" class="inventory-grid-classic">${slots}</div></div><div class="inventory-bottom-actions"><button class="inventory-bottom-action">重新整理</button><div class="inventory-pagination-slot"><div class="v141-inventory-pager"><button>←</button><span>1 / 5</span><button>→</button></div></div><button class="inventory-bottom-action inventory-quick-sell-action">一鍵售出</button></div></div></div></div></div></main><script>window.__qa=()=>{const q=s=>document.querySelector(s),r=e=>{const x=e.getBoundingClientRect();return {left:x.left,right:x.right,top:x.top,bottom:x.bottom,width:x.width,height:x.height}},title=q('.inventory-title-plate'),close=q('.map-inventory-overlay-close'),shell=q('.inventory-classic-shell'),slots=[...document.querySelectorAll('.inventory-item-classic')];return {title:q('h2').textContent,titleRect:r(title),closeRect:r(close),shell:r(shell),slots:slots.map(slot=>({rarity:[...slot.classList].find(c=>c.startsWith('rarity-')),border:getComputedStyle(slot).border,borderWidth:getComputedStyle(slot).borderWidth,borderStyle:getComputedStyle(slot).borderStyle})),arts:[...document.querySelectorAll('.v169-item-art')].map(art=>({material:art.classList.contains('v169-material-art'),borderWidth:getComputedStyle(art).borderWidth,borderStyle:getComputedStyle(art).borderStyle,shadow:getComputedStyle(art).boxShadow,animation:getComputedStyle(art).animationName}))};};</script></body></html>`;
fs.writeFileSync(fixture,html,"utf8");

(async()=>{const browser=await connectChrome(chrome);try{for(const [width,height] of [[360,800],[390,844],[412,915],[430,932]]){await browser.send("Emulation.setDeviceMetricsOverride",{width,height,deviceScaleFactor:1,mobile:true,screenWidth:width,screenHeight:height,screenOrientation:{type:"portraitPrimary",angle:0}});await browser.send("Page.navigate",{url:`file://${fixture}`});await sleep(220);const data=(await browser.send("Runtime.evaluate",{expression:"window.__qa()",returnByValue:true})).result.value;assert.equal(data.title,"背包");assert.ok(Math.abs(data.titleRect.left+data.titleRect.right-width)<2,`title not centered at ${width}`);assert.ok(data.closeRect.right<=data.shell.right&&data.closeRect.left>data.titleRect.right,`close geometry invalid at ${width}`);assert.equal(data.slots.length,24);for(const rarity of rarities){const slot=data.slots.find(row=>row.rarity===`rarity-${rarity}`);assert.equal(slot.borderWidth,"1px",`${rarity} must use one 1px outer frame`);assert.equal(slot.borderStyle,"solid",`${rarity} must use solid outer frame`);}for(const art of data.arts){assert.equal(art.borderWidth,"0px","inner artwork border leaked");assert.equal(art.borderStyle,"none","inner artwork border leaked");assert.equal(art.shadow,"none","inner artwork glow leaked");assert.equal(art.animation,"none","inner artwork animation leaked");}const shot=await browser.send("Page.captureScreenshot",{format:"png",fromSurface:true,captureBeyondViewport:false});const out=path.join(root,"artifacts/browser-qa",`backpack-${width}.png`);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,Buffer.from(shot.data,"base64"));}console.log("✓ Backpack Browser Visual QA passed: production CSS stack + single rarity frame 360/390/412/430px");}finally{browser.close();try{fs.unlinkSync(fixture);}catch(_){}}})().catch(error=>{console.error(error.stack||error);process.exitCode=1;});

// CI trigger: preserve semantic Backpack art border assertions.
