"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const css22=read("css/22-stage-v78-character-inventory-core.css");
const css23=read("css/23-stage-v77-inventory-detail-ui.css");
const css24=read("css/24-stage-v85-inventory-inner-grid-scroll-root.css");
const css31=read("css/31-v131-fix-batch.css");
const css38=read("css/38-v141-system-expansion.css");
const css50=read("css/50-v169-abyss-flow.css");
const browser=read("tests/backpack-visual-composition-browser.test.js");

// Permanent gate: source ownership checks are paired with full production-stack browser QA.
assert.match(css22,/--inventory-equipment-slot-size/);
assert.match(css22,/--inventory-equipment-cell-height/);
assert.match(css22,/#game-stage #inventoryPage #inventoryCharacterDetailButton\{[^}]*width:28px[^}]*height:28px/);
assert.doesNotMatch(css23,/inventory-character-detail-button/);
assert.doesNotMatch(css31,/inventoryCharacterDetailButton/);
assert.doesNotMatch(css24,/102-SLOT|102-slot|exactly 102|no pagination|height:100%|flex:1 1 auto !important/);
assert.match(css24,/inventoryGridScroll|inventory-grid-scroll/);
assert.match(css38,/inventory-backpack-rarity-neutral/);
assert.match(css50,/v169-item-art:not\(\.inventory-backpack-rarity-neutral\)/);
assert.match(browser,/build\/asset-manifest\.json/);
assert.match(browser,/gameplay-core/);
assert.match(browser,/v169-item-art v169-equipment-art/);
assert.match(browser,/equipment label/);
assert.match(browser,/art\.shadow/);
console.log("✓ Backpack Runtime CSS Owner convergence regression passed");
