"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=file=>fs.readFileSync(file,"utf8");
const feedback=read("js/battle-floating-feedback-owner.js");
const css=read("css/battle-floating-feedback-owner.css");
const geometry=read("js/battlefield-render-geometry-adapter.js");
const v143=read("js/39-v143-skill-animation.js");
const v146=read("js/41-v146-system-polish.js");
const main=read("js/00-main.js");
const mainCss=read("css/00-main.css");
const relic=read("js/60-team-relic-system.js");
const relicCss=read("css/55-team-relic-system.css");
assert.match(feedback,/STATUS_PRESENTATION_SEMANTICS/);
assert.match(feedback,/statusType/);
assert.match(feedback,/damageDown:Object\.freeze\(\{color:"#39c96b"/);
assert.match(feedback,/context\.queue\.sort\(compareRequests\)/);
assert.match(feedback,/impactId/);
assert.match(feedback,/skipImpactTiming:input\.skipImpactTiming===true/);
assert.match(feedback,/if\(request\.skipImpactTiming\)\{\s*pump\(context\);\s*return;/);
assert.match(css,/data-feedback-kind="status"/);
assert.match(css,/background:#0b0b0d/);
assert.match(v143,/impactId:current/);
assert.match(v143,/impactAt:Date\.now\(\)\+wait/);
assert.match(v146,/statusType:type/);
assert.match(geometry,/hpRect:hpRect/);
assert.match(geometry,/highlightRects:highlightRects/);
assert.match(geometry,/highlightRect:highlightRect/);
assert.doesNotMatch(feedback,/triggerCriticalImpact\(/);
assert.doesNotMatch(main,/triggerCriticalImpact\(/);
assert.doesNotMatch(mainCss,/critical-impact::before|criticalImpactBurst|damage-popup\.critical-popup/);
assert.doesNotMatch(relic,/team-relic-battle-target-outline/);
assert.doesNotMatch(relicCss,/team-relic-battle-target-outline/);
console.log("Battle feedback semantic/sequencing/geometry contracts passed.");
