"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=file=>fs.readFileSync(file,"utf8");
const feedback=read("js/battle-floating-feedback-owner.js");
const geometry=read("js/battlefield-render-geometry-adapter.js");
const relic=read("js/60-team-relic-system.js");
const relicCss=read("css/55-team-relic-system.css");
const skill=read("js/00-main.js");
const skillCss=read("css/battle-skill-name-presentation-owner.css");
const mainCss=read("css/00-main.css");
assert.match(feedback,/return "💥 "\+\(match\?match\[0\]:value\)/);
assert.match(feedback,/pendingImpacts/);
assert.match(feedback,/function registerImpact/);
assert.match(feedback,/function flushImpact/);
assert.doesNotMatch(feedback,/request\.delayTimer/);
assert.match(geometry,/spProjection/);
assert.match(geometry,/ratioFromRuntime/);
assert.doesNotMatch(geometry,/outerHTML|innerHTML/);
const projection=relic.slice(relic.indexOf("function appendRelicProjection"),relic.indexOf("function revealRelicTargets"));
assert.doesNotMatch(projection,/outerHTML|innerHTML/);
assert.match(projection,/team-relic-target-projection-resource/);
assert.match(projection,/spProjection/);
assert.match(relicCss,/team-relic-target-projection-sp/);
assert.match(skill,/badge\.style\.position="fixed"/);
assert.match(skill,/document\.body\.appendChild\(badge\)/);
assert.doesNotMatch(skill,/badgePoint\s*=\s*gamePointFromClient/);
assert.match(skillCss,/body > \.skill-name-badge/);
assert.match(skillCss,/font-size:var\(--battle-feedback-font-size\)/);
assert.doesNotMatch(mainCss,/\.skill-name-badge\s*\{/);
assert.doesNotMatch(mainCss,/skill-name-badge\{[\s\S]*position:absolute/);
console.log("Battle impact/resource/typography contracts passed.");
