"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const v154=read("js/45-v154-dev-fixes.js");
const v159=read("js/48-v159-abyss-battle-portraits.js");
const v148=read("js/42-v148-combat-dungeon-fixes.js");
const equipment=read("js/equipment-progression.js");
const presentation=read("js/54-v173.51-battle-qa.js");
const adapter=read("js/battlefield-render-geometry-adapter.js");
const css=read("css/fixed-slot-battlefield-rendering-v2.css");

assert.doesNotMatch(v154,/v162-abyss-battle-portrait-art|createElement\(["']img/);
assert.match(v154,/V174[\s\S]*sole visible artwork pipeline|sole visible artwork pipeline/);
assert.match(v154,/Promise\.all\(keys\.map/);
assert.match(v154,/dailyPortraitPreparation\.delete\(key\)/);
assert.match(v154,/monsterPortraitRegistryPromise=null/);
assert.match(v154,/monsterPortraitAssetFailures\.delete\(portraitKey\)/);
assert.doesNotMatch(v159,/requestAnimationFrame|setTimeout|v132LaunchDungeonBattle/);
assert.match(v159,/retired legacy portrait timing bridge/);
assert.match(v148,/window\.v148PrepareDailyDungeonLaunch=prepareDailyDungeonLaunch/);
assert.match(v148,/prepareDailyDungeonLaunch\(type,built\.waves\)/);
assert.match(equipment,/v148PrepareDailyDungeonLaunch\("gold",waves\)/);
assert.match(presentation,/FourSymbolsBattlePresentation=Object\.freeze/);
assert.match(presentation,/art\.style\.backgroundImage=source/);
assert.match(adapter,/window\.vFixedSlotAfterBattleRender=reconcile/);
assert.doesNotMatch(css,/v162-abyss-battle-portrait-art/);
assert.match(css,/\.v174-battle-art/);
console.log("Daily Dungeon Portrait Final Convergence contract: PASS");
