"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const main=fs.readFileSync("js/00-main.js","utf8");
const forge=fs.readFileSync("js/36-v141-content-systems.js","utf8");
const html=fs.readFileSync("index.html","utf8");
const equipmentBlock=main.slice(main.indexOf("function getEquipmentBonus(characterId){"),main.indexOf("/* =====================================================\n   V119",main.indexOf("function getEquipmentBonus(characterId){")));
const context={window:{},characterEquipment:{fire:{head:null}},console};
vm.createContext(context);
vm.runInContext(equipmentBlock,context);
const api=context.window.FourSymbolsEquipmentGems;
for(const [rarity,expected] of Object.entries({white:0,blue:0,purple:0,orange:1,pink:2,"four-symbol":3,red:2,myriad:3})){
    assert.equal(api.capacity({rarityKey:rarity}),expected,rarity);
}
assert.equal(api.capacity({rarityKey:"orange",sockets:["gemVitalityI"]}),1);
const old={rarityKey:"orange",stats:{attack:5}};
context.characterEquipment.fire.head=old;
assert.equal(context.getEquipmentBonus("fire").attack,5);
assert.equal(context.getEquipmentBonus("fire").vitality,0);
old.sockets=["gemVitalityI"];
assert.equal(context.getEquipmentBonus("fire").vitality,1);
old.sockets.push("gemVitalityI");
assert.equal(context.getEquipmentBonus("fire").vitality,1,"extra saved sockets cannot grant attributes");
context.characterEquipment.fire.head=null;
assert.equal(context.getEquipmentBonus("fire").vitality,0,"unequipping removes gem effects");
context.characterEquipment.fire.head={rarityKey:"pink",sockets:["gemVitalityI","gemVitalityI"]};
assert.equal(context.getEquipmentBonus("fire").vitality,2,"equipping another item reads its own sockets");
assert.match(html,/openHomeFeature\('forge'\)[^>]*aria-label="鍛造"/);
assert.doesNotMatch(html,/openHomeFeature\('bestiary'\)/);
assert.doesNotMatch(main,/function renderBestiaryContent\(/);
assert.match(main,/bestiaryData/);
const reforge=forge.slice(forge.indexOf("function reforgeMaterialInfo"),forge.indexOf("window.v141ResolveReforge"));
assert.doesNotMatch(reforge,/consumeMatching\(candidate=>candidate&&candidate.blueprintSlot/);
assert.doesNotMatch(forge.slice(forge.indexOf("function renderReforgeTab"),forge.indexOf("function availableTalismans")),/blueprintCount/);
assert.match(reforge,/v132ConsumeStackItem\(info.ore.id,cost\)/);
assert.match(forge,/sockets.length>capacity/);
const localSocketHelpers=forge.slice(forge.indexOf("    function canUseLocalSockets(){"),forge.indexOf("    function renderForgePicker("));
const socketOperation=forge.slice(forge.indexOf("window.v141SocketGem=function(){"),forge.indexOf("window.v141SwitchSynthesisTab",forge.indexOf("window.v141SocketGem=function(){")));
const gemStock={id:"gemVitalityI",count:2};
const gear={v141Uid:"gear-1",rarityKey:"orange",stats:{attack:5}};
let saved=0;
const metadata={ownerUid:"forge-qa",source:"local",cloudBaseFingerprint:null};
let saveFails=false;
const actionContext={window:{FourSymbolsEquipmentGems:api,FourSymbolsAccountSave:{readActive:()=>({status:"ready",uid:"forge-qa",metadata})},v132ConsumeStackItem:(id,n)=>{
    if(id!==gemStock.id||gemStock.count<n){ return false; }
    gemStock.count-=n;return true;
}},activeFeature:"forge",synthesisState:{socketUid:"gear-1",gemId:"gemVitalityI",pendingReforge:null},
    socketEquipment:()=>[{item:gear}],countItem:()=>gemStock.count,runInventoryTransaction:fn=>{const count=gemStock.count;try{if(fn()){return true;}}catch(_){}gemStock.count=count;return false;},
    rebuildInventorySlots:()=>{},saveGame:()=>{saved++;return !saveFails;},updateUI:()=>{},renderSynthesis:()=>{}};
vm.createContext(actionContext);
vm.runInContext(localSocketHelpers+socketOperation,actionContext);
assert.equal(actionContext.window.v141SocketGem(),true);
assert.equal(gear.sockets.length,1);
assert.equal(gemStock.count,1);
assert.equal(saved,1);
assert.equal(actionContext.window.v141SocketGem(),false,"capacity blocks a second gem and preserves inventory");
assert.equal(gemStock.count,1);
actionContext.synthesisState.gemId="missing";
assert.equal(actionContext.window.v141SocketGem(),false,"unknown gems cannot be embedded");
delete gear.sockets;
actionContext.synthesisState.gemId="gemVitalityI";
saveFails=true;
assert.equal(actionContext.window.v141SocketGem(),false,"failed save rolls back gem and socket");
assert.equal(gemStock.count,1);
assert.equal(Object.hasOwn(gear,"sockets"),false);
saveFails=false;
metadata.cloudBaseFingerprint="v1:cloud-base";
assert.equal(actionContext.window.v141SocketGem(),false,"authoritative cloud cache cannot use local mutation");
metadata.cloudBaseFingerprint=null;
metadata.ownerUid="another-uid";
assert.equal(actionContext.window.v141SocketGem(),false,"ownership mismatch fails closed");
metadata.ownerUid="forge-qa";
gear.sockets=["missing"];
assert.equal(actionContext.window.v141SocketGem(),false,"invalid saved slots cannot be overwritten");
assert.equal(gemStock.count,1);
gear.rarityKey="pink";
gear.sockets=[null,"gemVitalityI"];
assert.equal(actionContext.window.v141SocketGem(),true,"explicit empty slot is filled without exceeding capacity");
assert.deepEqual(Array.from(gear.sockets),["gemVitalityI","gemVitalityI"]);
assert.equal(gemStock.count,0);
const loaded=JSON.parse(JSON.stringify(gear));
assert.deepEqual(loaded.sockets,["gemVitalityI","gemVitalityI"],"existing JSON equipment save retains sockets");
assert.equal(api.capacity({quality:"unrecognized",tierKey:"orange"}),1,"fallback follows existing rarity field order");
assert.equal(api.capacity({legacyTierKey:"perfect"}),1);
assert.equal(api.capacity({rarityKey:"white",tierKey:"orange"}),0,"explicit canonical rarity takes precedence");
assert.equal(api.stats({rarityKey:"orange",sockets:[{toString:()=>"gemVitalityI"}]}).length,0);
const socketRender=forge.slice(forge.indexOf("    function renderSocketTab(){"),forge.indexOf("    function inferTier("));
assert.doesNotMatch(socketRender,/<select|<option/);
assert.match(socketRender,/renderForgePicker/);
console.log("✓ forge sockets, save compatibility, equip bonuses, and blueprint-free reforge");
