"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=p=>fs.readFileSync(p,"utf8");
const inventoryJs=read("js/35-v141-ui-battle.js");
const inventoryQol=read("js/53-v173.50-inventory-qol.js");
const scrollOwner=read("js/19-stage-v78-character-inventory-runtime.js");
const relicJs=read("js/60-team-relic-system.js");
const inventoryCss=read("css/22-stage-v78-character-inventory-core.css");
const detailCss=read("css/23-stage-v77-inventory-detail-ui.css");
const systemCss=read("css/38-v141-system-expansion.css");
const relicCss=read("css/55-team-relic-system.css");
assert.match(inventoryJs,/const INVENTORY_PAGE_SIZE=18;/);
assert.match(inventoryJs,/const INVENTORY_PAGE_COUNT=7;/);
assert.match(inventoryJs,/slice\(\s*inventoryPageIndex\*INVENTORY_PAGE_SIZE/);
assert.match(inventoryQol,/QUALITY_ORDER=\["white","blue","purple","orange","pink","four-symbol"\]/);
assert.match(scrollOwner,/inventoryOwnsScroll/);
assert.match(scrollOwner,/inventoryOwnsScroll\s*\?\s*"hidden"\s*:\s*"scroll"/);
assert.match(relicJs,/function prepareRelicModal\(\)/);
assert.match(inventoryCss,/inventory-grid-classic\{[\s\S]*?repeat\(6,minmax\(0,1fr\)\)/);
assert.match(inventoryCss,/inventory-item-classic\{[\s\S]*?border-width:1px !important;[\s\S]*?box-sizing:border-box/);
assert.match(detailCss,/inventory-stat-primary\{[\s\S]*?border-bottom:1px solid rgba\(200,154,72,.12\)/);
assert.match(detailCss,/inventory-character-detail-row\{[\s\S]*?min-height:44px/);
assert.match(systemCss,/\.item-modal \.item-modal-box\{[\s\S]*?border:1px solid rgba\(200,154,72,.72\)/);
assert.match(relicCss,/team-relic-current-actions button,#game-stage \.team-relic-select-first\{[\s\S]*?min-height:44px/);
assert.match(relicCss,/team-relic-tabs button\{[\s\S]*?min-height:44px/);
assert.match(relicCss,/\.rarity-white\{border-color:#d8d8d8!important;/);
assert.match(relicCss,/\.rarity-blue\{border-color:#42a5ff!important;/);
assert.match(relicCss,/\.rarity-purple\{border-color:#B05CFF!important;/);
assert.match(relicCss,/\.rarity-orange\{border-color:#FF9F38!important;/);
assert.match(relicCss,/\.rarity-pink\{border-color:#FF4FA7!important;/);
assert.match(relicCss,/rarity-four-symbol/);
console.log("✓ premium functional UI batch 3 preserves 18x7 inventory, item and relic runtimes");
