"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=p=>fs.readFileSync(p,"utf8");
const shop=read("css/49-v169-rpg-ui.css");
const synth=read("css/38-v141-system-expansion.css");
const economy=read("js/28-v133-economy-rebalance.js");
const shopRuntime=read("js/40-v144-rules-and-abyss.js");
const synthesis=read("js/36-v141-content-systems.js");
const fixes=read("js/58-v173.63-functional-fixes.js");
const ui=read("js/51-v169-rpg-ui.js");
const materialRule=(synth.match(/#game-stage \.v141-material-lines span\{[^{}]*\}/)||[""])[0];
assert.match(shop,/#homeFeatureModal\.v131-shop-open \.v17345-shop-tabs button\{[^{}]*min-height:44px !important;[^{}]*height:44px !important/);
assert.match(shop,/\.shop-potion-purchase-row \.shop-potion-buy\{[^{}]*min-height:42px !important;[^{}]*#f1ce7a/);
assert.match(shop,/\.v17346-shop-card \.v17346-shop-buy\{[^{}]*min-height:42px !important;[^{}]*#f1ce7a/);
assert.match(shop,/v141-synthesis-modal \.v141-synthesis-tabs button\{[^{}]*min-height:44px !important/);
assert.match(materialRule,/border-bottom:1px solid rgba\(200,154,72,.14\)/);
assert.match(materialRule,/background:transparent/);
assert.match(synth,/\.v141-material-lines \.lack\{color:#ee8e79;/);
assert.match(synth,/\.v141-synthesis-primary\{[^{}]*min-height:44px !important/);
assert.match(synth,/\.v141-reforge-compare button\{[^{}]*min-height:44px/);
assert.match(synth,/\.v141-synthesis-body\{[^{}]*overflow-y:auto[^{}]*touch-action:pan-y/);
assert.match(synthesis,/\["reforge","裝備冶煉"\]/);
assert.match(synthesis,/\["talisman","符咒合成"\]/);
assert.match(synthesis,/\["fragment","碎片合成"\]/);
assert.match(fixes,/ensureMaterialTab/);
assert.match(shopRuntime,/shopUnitPrice/);
assert.match(economy,/gold/);
assert.match(ui,/shop-potion-card/);
console.log("✓ premium functional UI batch 4 preserves shop transactions and synthesis/reforge runtimes");
