"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=p=>fs.readFileSync(p,"utf8");
const html=read("index.html");
const main=read("js/00-main.js");
const growth=read("js/41-v146-system-polish.js");
const base=read("css/00-main.css");
const exp=read("css/31-v131-fix-batch.css");
const expShell=read("css/38-v141-system-expansion.css");
assert.match(html,/id="expDistributeList"/);
assert.match(html,/id="attributePoints"/);
assert.match(html,/id="confirmStatusButton"[\s\S]*?onclick="confirmStatus\(\)"/);
assert.match(main,/function renderExpDistributeList\(\)/);
assert.match(main,/function addPoint\(/);
assert.match(main,/function removePoint\(/);
assert.match(main,/function confirmStatus\(\)/);
["attack","intelligence","vitality","energy","spirit","agility"].forEach(stat=>assert.match(main,new RegExp(stat)));
assert.match(growth,/characterTabBtnExpPool/);
assert.match(growth,/characterTabBtnStatus/);
assert.match(growth,/characterTabBtnSkill/);
assert.match(growth,/homeExpPoolCard/);
assert.match(growth,/statusPage/);
assert.match(growth,/skillPage/);
assert.match(base,/\.status-btn\{[\s\S]*?width:44px;[\s\S]*?height:44px/);
assert.match(base,/\.status-confirm\{[\s\S]*?min-height:44px/);
assert.match(base,/\.skill-action-card\{[\s\S]*?min-height:44px/);
assert.match(exp,/\.v131-exp-preview-btn\{[\s\S]*?min-height:44px/);
assert.match(exp,/\.v131-exp-actions button\{[\s\S]*?min-height:44px/);
assert.match(expShell,/#game-stage #homeExpPoolCard \.exp-pool-hero\{[\s\S]*?rgba\(200,154,72,.30\)/);
console.log("✓ premium functional UI batch 2 preserves EXP, leveling, six-stat allocation and skill owners");
