"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=p=>fs.readFileSync(p,"utf8");
const main=read("js/00-main.js");
const core=read("js/34-v141-core-systems.js");
const ui=read("js/35-v141-ui-battle.js");
const rpg=read("js/51-v169-rpg-ui.js");
const questRuntime=read("js/57-v173.51-quest-qa.js");
const saves=read("js/startup/account-save-repository.js");
const shared=read("css/49-v169-rpg-ui.css");
const info=read("css/38-v141-system-expansion.css");
const quest=read("css/25-stage-v90-quest-interface-core.css");
const qa=read("css/53-v173.51-qa.css");
assert.match(main,/function renderBestiaryContent\(\)/);
assert.match(main,/bestiaryData/);
assert.match(main,/achievementState/);
assert.match(main,/type==="bestiary"/);
assert.match(main,/type==="announcement"/);
assert.match(ui,/ANNOUNCEMENT_READ_KEY=window\.FourSymbolsAccountSave\.accountKey\("announcement-read"\)/);
assert.match(saves,/v141_announcement_read:"announcement-read"/);
assert.match(core,/achievement/);
assert.match(questRuntime,/quest/);
assert.match(rpg,/window\.rpgAlert=function/);
assert.match(rpg,/window\.rpgConfirm=function/);
assert.match(rpg,/event\.key!=="Escape"/);
assert.match(rpg,/previousFocus/);
assert.match(shared,/\.v169-rpg-dialog::before,[\s\S]*?pointer-events:none/);
assert.match(shared,/\.v169-rpg-dialog-crest\{[\s\S]*?pointer-events:none/);
assert.match(shared,/announcement is a reading surface/);
assert.match(shared,/home-feature-modal-box::before,[\s\S]*?pointer-events:none/);
assert.match(info,/#homeFeatureModalBody \.home-feature-row\{[\s\S]*?border-bottom:1px solid rgba\(200,154,72,.14\)[\s\S]*?background:transparent/);
assert.match(quest,/quest-tab\{[\s\S]*?min-height:44px !important/);
assert.match(quest,/quest-tab-body\{[\s\S]*?overflow-y:auto[\s\S]*?touch-action:pan-y/);
assert.match(quest,/quest-claim-btn\{[\s\S]*?min-height:44px !important/);
assert.match(qa,/v17351-achievement-claim-all\{[^{}]*min-height:44px!important/);
assert.match(qa,/v17351-achievement-card>button\{[^{}]*min-height:44px!important/);
assert.match(qa,/v17351-achievement-pager button\{[^{}]*min-height:44px!important/);
assert.match(qa,/quest-mode \.quest-tab\{[^{}]*min-height:44px!important/);
assert.match(qa,/quest-mode \.quest-claim-btn\{[^{}]*min-height:44px!important/);
console.log("✓ premium functional UI batch 5 preserves achievement, announcement, bestiary, quest and modal runtimes");
