"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=p=>fs.readFileSync(p,"utf8");
const inventoryCss=read("css/38-v141-system-expansion.css");
const abyssCss=read("css/50-v169-abyss-flow.css");
const inventoryJs=read("js/35-v141-ui-battle.js");
const battle=read("js/54-v173.51-battle-qa.js");
const battlefieldCss=read("css/fixed-slot-battlefield-rendering-v2.css");
const vfx=read("js/39-v143-skill-animation.js");
const vfxCss=read("css/40-v143-combat-dungeon-polish.css");
const bossCss=read("css/gameplay-boss-tower.css");
const bossJs=read("js/gameplay-boss-tower-system.js");
const fireCss=read("css/56-v174-critical-ui-regressions.css");
const legacyNav=read("js/38-v143-system-fixes.js");
const finalNav=read("js/42-v148-combat-dungeon-fixes.js");
assert.match(inventoryJs,/const INVENTORY_PAGE_SIZE=18;/);
assert.match(inventoryJs,/for\(let index=0;index<INVENTORY_PAGE_SIZE;index\+\+\)/);
assert.match(inventoryCss,/inventory-grid-classic[\s\S]*grid-template-columns:repeat\(6,minmax\(0,1fr\)\)/);
assert.match(inventoryCss,/inventory-grid-classic \.inventory-item-classic \.inventory-icon > \.v169-item-art[\s\S]*object-fit:contain/);
assert.doesNotMatch(abyssCss,/#game-stage #inventoryPage \.inventory-item-classic \.inventory-icon > \.v169-item-art\{/);
assert.doesNotMatch(battle,/battle-monster\.v174-cardless-unit>\.battle-monster-name\{[\s\S]*top:0!important/,
    "legacy V173.51 runtime must not move enemy names above the card");
assert.match(battlefieldCss,/\.v-fixed-enemy-slot \.battle-monster-name\{[\s\S]*bottom:21px !important;[\s\S]*z-index:24 !important/,
    "the Fixed Slot layout owner must keep enemy names below their artwork");
assert.match(battlefieldCss,/\.v-fixed-battle-slot > \.battle-monster > \.v174-battle-art,[\s\S]*bottom:var\(--battle-art-hud-reserve\) !important/,
    "the Fixed Slot layout owner must reserve card-bottom HUD space");
assert.match(battlefieldCss,/battle-player\.v174-cardless-unit\.active-turn\{[\s\S]*outline:2px solid #f1c96d !important/);
assert.match(vfx,/const SPRITE_SCALE_MULTIPLIER=1;/);
assert.doesNotMatch(vfx,/function visualRectForCard\(/,"VFX geometry must not regress to character/art DOM bounds");
assert.match(vfx,/function geometryOwner\(\)\{[\s\S]*window\.FourSymbolsBattlefieldSlots/);
assert.match(vfx,/function geometryBounds\([\s\S]*owner\.getSideRect[\s\S]*owner\.getGeometryRectFromShape/);
assert.match(vfx,/node\.dataset\.geometryOwner="fixed-slot"/);
assert.match(vfx,/function applySpriteBox\([\s\S]*SPRITE_SCALE_MULTIPLIER/);
assert.match(vfx,/naturalWidth[\s\S]*columns[\s\S]*naturalHeight[\s\S]*rows/);
assert.match(vfx,/node\.style\.visibility="hidden"/);
assert.match(vfx,/function confirmTargetVisual/);
assert.match(vfx,/window\.v143RunAtTargetHit=function\(targetSide,index,callback,allowDefeated\)\{[\s\S]*const wait=delayFor\(targetSide,index,allowDefeated===true\);[\s\S]*setTimer\(callback,wait\)/);
assert.match(vfx,/popup\.classList\.add\("v152-top-damage"\)/);
assert.match(bossCss,/--gameplay-mechanism-card-width:clamp\(123px,30%,138px\)/);
assert.match(bossCss,/--gameplay-mechanism-card-width:clamp\(117px,29\.25%,132px\)/);
assert.match(bossJs,/showDamagePopup\(node,"HP-"\+final,"hp",!!isCrit\)/);
assert.match(vfxCss,/@keyframes v143RasterTravel\{[\s\S]*rotate\(var\(--v143-sprite-angle,0deg\)\)/);
assert.doesNotMatch(fireCss,/v174FireRocketTravel/);
assert.doesNotMatch(fireCss,/data-skill="fireRocket"/);
assert.doesNotMatch(legacyNav,/function fixDungeonNavigation\(\)\{[\s\S]*?nav\.innerHTML=/);
assert.match(legacyNav,/v148SyncDungeonShell/);
assert.match(finalNav,/function contextNavMatches\(nav,returnAction\)/);
assert.match(finalNav,/\["秘寶","assets\/ui\/nav-relic-v175\.webp","v148OpenContextRelic\(\)"\]/);
assert.match(finalNav,/buttons\.push\(\["返回","assets\/ui\/map-return\.png",returnAction\]\)/);
assert.match(finalNav,/const mode=gameplayActive&&!dungeonActive[\s\S]*?"gameplay:"\+gameplayPageId[\s\S]*?"abyss-map"[\s\S]*?"abyss-selection"[\s\S]*?"daily"/);
assert.match(finalNav,/window\.v148SyncContextNavigation=syncContextNavigation/);
assert.doesNotMatch(finalNav,/\["商店","assets\/ui\/home-shop-v147\.png"/);
console.log("✓ remaining UI regressions guarded");
