"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=p=>fs.readFileSync(p,"utf8");
const inventoryCss=read("css/38-v141-system-expansion.css");
const abyssCss=read("css/50-v169-abyss-flow.css");
const inventoryJs=read("js/35-v141-ui-battle.js");
const battle=read("js/54-v173.51-battle-qa.js");
const vfx=read("js/39-v143-skill-animation.js");
const vfxCss=read("css/40-v143-combat-dungeon-polish.css");
const bossCss=read("css/gameplay-boss-tower.css");
const bossJs=read("js/gameplay-boss-tower-system.js");
const fireCss=read("css/56-v174-critical-ui-regressions.css");
const legacyNav=read("js/38-v143-system-fixes.js");
const finalNav=read("js/42-v148-combat-dungeon-fixes.js");
assert.match(inventoryJs,/const INVENTORY_PAGE_SIZE=18;/);
assert.match(inventoryJs,/for\(let index=0;index<INVENTORY_PAGE_SIZE;index\+\+\)/);
assert.match(inventoryCss,/inventory-grid-classic[\s\S]*grid-template-columns:repeat\(6,minmax\(0,1fr\)\)/);
assert.match(inventoryCss,/inventory-grid-classic \.inventory-item-classic \.inventory-icon > \.v169-item-art[\s\S]*object-fit:contain/);
assert.doesNotMatch(abyssCss,/#game-stage #inventoryPage \.inventory-item-classic \.inventory-icon > \.v169-item-art\{/);
/* Monster identity stays below its own thin HP/SP HUD without inflating the fixed formation rows; art remains fully contained. */
assert.match(battle,/battle-monster\.v174-cardless-unit>\.battle-monster-name\{[\s\S]*top:auto!important;bottom:0!important;[\s\S]*z-index:24!important/);
assert.match(battle,/battle-monster\.v174-cardless-unit>\.v174-battle-art\{[\s\S]*inset:2px 2px 42px!important;[\s\S]*background-size:contain!important/);
assert.match(battle,/battle-player\.v174-cardless-unit>\.v174-battle-art\{[\s\S]*inset:-2px -2px 30px!important;[\s\S]*background-size:contain!important/);
assert.match(battle,/battle-monster\.v174-cardless-unit>\.monster-hp,[\s\S]*battle-monster\.v174-cardless-unit>\.monster-sp\{[\s\S]*height:11px!important/);
assert.match(battle,/battle-player\.v174-cardless-unit\.active-turn\{[\s\S]*outline:2px solid #f1c96d!important/);
assert.match(vfx,/const SPRITE_SCALE_MULTIPLIER=1;/);
assert.match(vfx,/function visualRectForCard\(card\)[\s\S]*:scope > \.v174-battle-art/);
assert.match(vfx,/function applySpriteBox\([\s\S]*SPRITE_SCALE_MULTIPLIER/);
assert.match(vfx,/naturalWidth[\s\S]*columns[\s\S]*naturalHeight[\s\S]*rows/);
assert.match(vfx,/node\.style\.visibility="hidden"/);
assert.match(vfx,/className="v143-vfx-frame"/);
assert.match(vfx,/function confirmTargetVisual/);
assert.match(vfx,/window\.v143RunAtTargetHit=function\(targetSide,index,callback,allowDefeated\)\{[\s\S]*const wait=delayFor\(targetSide,index,allowDefeated===true\);[\s\S]*setTimer\(callback,wait\)/);
assert.match(vfx,/popup\.classList\.add\("v152-top-damage"\)/);
assert.match(vfxCss,/\.v143-skill-stage\{[\s\S]*overflow:visible;[\s\S]*contain:layout style;/);
assert.match(vfxCss,/\.v143-vfx-frame\{[\s\S]*overflow:hidden;/);
assert.match(bossCss,/--gameplay-mechanism-card-width:clamp\(123px,30%,138px\)/);
assert.match(bossCss,/--gameplay-mechanism-card-width:clamp\(117px,29\.25%,132px\)/);
assert.match(bossJs,/showDamagePopup\(node,"HP-"\+final,"hp",!!isCrit\)/);
assert.match(vfxCss,/@keyframes v143RasterTravel\{[\s\S]*rotate\(var\(--v143-sprite-angle,0deg\)\)/);
assert.doesNotMatch(fireCss,/v174FireRocketTravel/);
assert.doesNotMatch(fireCss,/data-skill="fireRocket"/);
assert.doesNotMatch(legacyNav,/function fixDungeonNavigation\(\)\{[\s\S]*?nav\.innerHTML=/);
assert.match(legacyNav,/v148SyncDungeonShell/);
/* V148 is the one markup owner for both Gameplay and Dungeon contexts. */
assert.match(finalNav,/function contextNavMatches\(nav,returnAction\)/);
assert.match(finalNav,/\["秘寶","assets\/ui\/nav-relic-v175\.webp","openHomeFeature\(\'relic\'\)"\]/);
assert.match(finalNav,/buttons\.push\(\["返回","assets\/ui\/map-return\.png",returnAction\]\)/);
assert.match(finalNav,/const mode=gameplayActive&&!dungeonActive[\s\S]*?"gameplay:"\+gameplayPageId[\s\S]*?"abyss-map"[\s\S]*?"abyss-selection"[\s\S]*?"daily"/);
assert.match(finalNav,/window\.v148SyncContextNavigation=syncContextNavigation/);
assert.doesNotMatch(finalNav,/\["商店","assets\/ui\/home-shop-v147\.png"/);
console.log("✓ remaining UI regressions guarded");
