"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const touch=fs.readFileSync("js/01-stage-v8-touch-lock.js","utf8");
const nav=fs.readFileSync("js/04-stage-v11-native-bottom-nav-runtime.js","utf8");
const mapNav=fs.readFileSync("js/05-stage-v13-native-map-nav-runtime.js","utf8");
const loader=fs.readFileSync("js/20-anonymous-20.js","utf8");
const navCss=fs.readFileSync("css/09-stage-v15-native-character-shell.css","utf8");
assert.match(touch,/TAP_SLOP_CSS_PX=10/);
assert.match(touch,/pointerId:event\.pointerId,startX:event\.clientX,startY:event\.clientY,currentX:event\.clientX,currentY:event\.clientY/);
assert.match(touch,/state:"TAP"/);
assert.match(touch,/"DRAG"/);
assert.match(touch,/"SCROLL"/);
assert.match(touch,/"CANCEL"/);
assert.match(touch,/document\.addEventListener\("click"[\s\S]*?stopImmediatePropagation/);
assert.doesNotMatch(touch,/allowedSelector|scrollWhitelist/);
assert.doesNotMatch(nav,/mapPageNav/);
assert.match(mapNav,/function migrateMapNav/);
assert.doesNotMatch(loader,/element\.click\(\)/);
assert.match(loader,/createNavigationIntent/);
assert.match(navCss,/\.native-bottom-nav > #bottomNav/);
assert.doesNotMatch(navCss,/\.native-bottom-nav-shell/);
console.log("✓ touch gesture, nav owner, and lazy navigation intent contract");
