"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const touch=fs.readFileSync("js/01-stage-v8-touch-lock.js","utf8");
const nav=fs.readFileSync("js/04-stage-v11-native-bottom-nav-runtime.js","utf8");
const loader=fs.readFileSync("js/20-anonymous-20.js","utf8");
const navCss=fs.readFileSync("css/09-stage-v15-native-character-shell.css","utf8");
assert.match(touch,/TAP_SLOP_CSS_PX=10/);
assert.match(touch,/pointerId:event\.pointerId,startX:event\.clientX,startY:event\.clientY,currentX:event\.clientX,currentY:event\.clientY/);
assert.match(touch,/state:"TAP"/);
assert.match(touch,/"DRAG"/);
assert.match(touch,/"SCROLL"/);
assert.match(touch,/"CANCEL"/);
assert.match(touch,/game-stage[\s\S]*?addEventListener\("click",handleSuppressedGestureClick,true\)/);
assert.doesNotMatch(touch,/document\.addEventListener\s*\(\s*["']click["']/);
assert.doesNotMatch(touch,/allowedSelector|scrollWhitelist/);
assert.doesNotMatch(nav,/mapPageNav/);
assert.doesNotMatch(nav,/migrateMapNav|mapPageNav|v141DungeonNav/);
assert.doesNotMatch(loader,/element\.click\(\)/);
assert.match(loader,/createNavigationIntent/);
assert.doesNotMatch(navCss,/native-bottom-nav > #bottomNav/);
assert.match(fs.readFileSync("css/06-stage-v11-native-bottom-nav.css","utf8"),/native-bottom-nav-layer > #bottomNav/);
console.log("✓ touch gesture, nav owner, and lazy navigation intent contract");
