"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const {spawnSync}=require("node:child_process");
function findChrome(){for(const name of ["google-chrome","google-chrome-stable","chromium","chromium-browser"]){const p=spawnSync("bash",["-lc",`command -v ${name}`],{encoding:"utf8"});if(p.status===0&&p.stdout.trim())return p.stdout.trim();}return "";}
function decode(v){return v.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'");}
const file=path.join(process.cwd(),".creation-critical-browser.html");
const html=`<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="css/29-v125-character-creation-native.css"><link rel="stylesheet" href="css/56-v174-critical-ui-regressions.css"><style>html,body{margin:0;width:1080px;height:1920px;background:#000;overflow:hidden}#creationPage{display:block!important}</style></head><body>
<div id="creationPage" class="creation-page-scroll native-creation-page" data-element="water"><div class="creation-premium-shell"><header class="creation-premium-header"><div class="creation-header-ornament">◆</div><h1 class="creation-title">創建角色</h1><p class="creation-subtitle">選擇你的元素之道</p><div class="creation-step-progress"><span>01 選擇角色</span><i></i><span>02 能力配點</span></div></header><div class="creation-step is-active"><section class="creation-showcase"><div class="creation-portrait-panel"><div class="creation-portrait-aura"></div><img class="creation-portrait-image" src="assets/characters/female_water.jpg"><div class="creation-portrait-caption"><b>水元素</b><span>女俠</span></div></div><div class="creation-choice-panel"><div class="creation-section-kicker">性別</div><div class="creation-gender-grid"><button class="creation-gender-option selected">女</button><button class="creation-gender-option">男</button></div><div class="creation-section-kicker creation-element-kicker">元素</div><div class="creation-element-grid"><button class="element-option selected"><span class="creation-element-glyph">水</span><span class="element-name">寒水</span></button><button class="element-option"><span class="creation-element-glyph">火</span><span class="element-name">烈焰</span></button><button class="element-option"><span class="creation-element-glyph">風</span><span class="element-name">疾風</span></button><button class="element-option"><span class="creation-element-glyph">土</span><span class="element-name">厚土</span></button></div><div class="creation-role-card"><div class="creation-role-title-row"><div class="creation-element-badge">水</div><div><div class="creation-role-title">寒水之道</div><div class="creation-role-subtitle">吸取回復 · 冰封 · 治療復活</div></div></div><div class="creation-role-description">兼具續航、控場與隊伍回復；攻擊技能可吸取HP與SP，並擁有冰封、治療與復活能力。</div><div class="creation-role-tags"><span class="creation-role-tag">HP/SP吸取</span><span class="creation-role-tag">冰封控場</span><span class="creation-role-tag">治療復活</span></div></div></div></section><section class="creation-card creation-identity-card"><div class="creation-card-heading"><div class="creation-card-index">01</div><div><div class="creation-label">玩家 ID</div><div class="creation-card-caption">這會成為你的角色名稱</div></div></div><input class="creation-input" value="測試角色"></section><button class="creation-next"><span>下一步：能力配點</span></button></div></div></div>
<pre id="result"></pre><script>(function(){function r(s){var x=document.querySelector(s).getBoundingClientRect();return {top:x.top,bottom:x.bottom,left:x.left,right:x.right,width:x.width,height:x.height};}var showcase=r('.creation-showcase'),portrait=r('.creation-portrait-panel'),image=r('.creation-portrait-image'),role=r('.creation-role-card'),identity=r('.creation-identity-card'),next=r('.creation-next'),roleEl=document.querySelector('.creation-role-card');document.getElementById('result').textContent=JSON.stringify({showcase:showcase,portrait:portrait,image:image,role:role,identity:identity,next:next,hint:getComputedStyle(roleEl,'::after').content,objectFit:getComputedStyle(document.querySelector('.creation-portrait-image')).objectFit,overflowY:getComputedStyle(document.querySelector('.creation-role-card')).overflowY});})();</script></body></html>`;
fs.writeFileSync(file,html,"utf8");
try{const chrome=findChrome();if(!chrome){if(process.env.CI)throw new Error("CI must provide Chrome for creation browser QA");console.log("creation browser QA skipped");try{fs.unlinkSync(file);}catch(_){}process.exit(0);}const run=spawnSync(chrome,["--headless=new","--no-sandbox","--disable-gpu","--disable-dev-shm-usage","--allow-file-access-from-files","--force-device-scale-factor=1","--window-size=1080,1920","--dump-dom","file://"+file.replace(/\\/g,"/")],{encoding:"utf8",timeout:30000,maxBuffer:12*1024*1024});assert.equal(run.status,0,run.stderr);const m=run.stdout.match(/<pre id="result">([\s\S]*?)<\/pre>/);assert.ok(m);const d=JSON.parse(decode(m[1]));assert.equal(d.objectFit,"contain");assert.ok(d.image.top>=d.portrait.top-1&&d.image.bottom<=d.portrait.bottom+1,"portrait art is clipped outside its panel");assert.ok(d.role.top>=d.showcase.top&&d.role.bottom<=d.showcase.bottom+1,"element description escapes showcase");assert.ok(d.identity.top>=d.showcase.bottom-1,"identity card overlaps showcase");assert.ok(d.next.bottom<=1920+1,"creation next button escapes 1920 canvas");assert.match(d.hint,/土剋水/);console.log("✓ creation portrait/copy browser geometry passed");}finally{try{fs.unlinkSync(file);}catch(_){}}
