"use strict";

const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const {spawnSync}=require("node:child_process");

function chrome(){
    for(const name of ["google-chrome","google-chrome-stable","chromium","chromium-browser"]){
        const probe=spawnSync("bash",["-lc",`command -v ${name}`],{encoding:"utf8"});
        if(probe.status===0&&probe.stdout.trim()){ return probe.stdout.trim(); }
    }
    return "";
}
function decode(value){return value.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'");}
function fixture(width,height){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="css/00-main.css"><link rel="stylesheet" href="css/56-v174-critical-ui-regressions.css"><link rel="stylesheet" href="css/57-v174-current-ui-fixes.css">
<link rel="stylesheet" href="css/22-stage-v78-character-inventory-core.css"><link rel="stylesheet" href="css/42-v146-system-polish.css"><link rel="stylesheet" href="css/43-v148-combat-dungeon-fixes.css"><link rel="stylesheet" href="css/50-v169-abyss-flow.css"><link rel="stylesheet" href="css/gameplay-boss-tower.css"><link rel="stylesheet" href="css/55-team-relic-system.css">
<style>html,body{margin:0;width:${width}px;height:${height}px;overflow:hidden;background:#050505}#game-stage{position:relative;width:${width}px;height:${height}px;overflow:hidden}.qa-normal-card{width:80px;height:82px}.team-relic-home-tools{position:relative!important;left:0!important;transform:none!important;bottom:auto!important}#v146HomeRoster{position:relative!important}.gameplay-large-panel{height:160px!important}#inventoryPage{display:block!important;width:390px!important;height:160px!important;padding:0!important}.inventory-grid-classic{width:360px!important}.inventory-icon{width:100%!important;height:100%!important}#allElementSkillPreviewModal{display:block!important}#allElementSkillPreviewModal .skill-preview-body,.v17361-reward-preview{width:350px}</style></head><body><div id="game-stage">
<div id="homePage"><button class="home-card home-card-secondary qa-normal-card"><span class="home-card-icon"></span><span id="normalLabel" class="home-card-label">系統</span></button><div class="home-utility-actions team-relic-home-tools"><button class="home-card home-card-utility team-relic-home-entry"><span class="home-card-icon"></span><span id="relicLabel" class="home-card-label">秘寶</span></button><button class="home-card home-card-utility team-element-box-home-entry"><span class="home-card-icon"></span><span id="elementLabel" class="home-card-label">元素匣</span></button></div><section id="v146HomeRoster" class="v146-home-roster"><header>冒險隊伍</header><div class="v146-home-character">角色</div></section></div>
<div id="gameplayPage"><section class="gameplay-large-panel"><header class="gameplay-panel-header"><div><small>特殊戰鬥總覽</small><h2>玩法</h2></div></header></section></div>
<div id="allElementSkillPreviewModal"><div id="skillBody" class="skill-preview-body"></div></div>
<div id="inventoryPage"><div class="inventory-grid-classic"><button class="inventory-item-classic"><span class="inventory-icon"><span id="equipmentArt" class="v169-item-art v169-equipment-art v169-rarity-blue"><img id="equipmentImg" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100'%3E%3Crect width='100' height='100' fill='%23c88f30'/%3E%3C/svg%3E"></span></span></button></div></div>
<div class="v17361-reward-preview"><div id="rewardVisual" class="v17361-reward-visual equipment"><div id="rewardIcon" class="v17361-reward-icon rarity-white"><img><em>40%</em></div></div><div id="chestCount" class="v17361-chest-count">×2</div></div><pre id="result"></pre></div>
<script>window.showPage=name=>window.__qaPage=name;</script><script src="js/62-v174-current-ui-fixes.js"></script><script>document.dispatchEvent(new Event("DOMContentLoaded"));(function(){const q=s=>document.querySelector(s),r=e=>{const x=e.getBoundingClientRect();return {left:x.left,right:x.right,width:x.width,height:x.height}};const back=q('.v174-gameplay-home-back');if(back)back.click();const normal=getComputedStyle(q('#normalLabel'));const relic=getComputedStyle(q('#relicLabel'));q('#result').textContent=JSON.stringify({labels:{normal:normal.fontSize,normalLine:normal.lineHeight,relic:relic.fontSize,relicLine:relic.lineHeight,element:getComputedStyle(q('#elementLabel')).fontSize},roster:{marginTop:getComputedStyle(q('#v146HomeRoster')).marginTop,gap:getComputedStyle(q('#v146HomeRoster')).gap,charHeight:r(q('.v146-home-character')).height},gameplay:{count:document.querySelectorAll('.v174-gameplay-home-back').length,page:window.__qaPage||'',back:back?r(back):null,header:r(q('.gameplay-panel-header'))},hint:{font:getComputedStyle(q('#skillBody'),'::before').fontSize,content:getComputedStyle(q('#skillBody'),'::before').content},equipment:{cell:r(q('.inventory-item-classic')),art:r(q('#equipmentArt')),img:r(q('#equipmentImg')),fit:getComputedStyle(q('#equipmentImg')).objectFit,transform:getComputedStyle(q('#equipmentImg')).transform},preview:{icon:getComputedStyle(q('#rewardIcon')).display,chest:getComputedStyle(q('#chestCount')).display,content:getComputedStyle(q('#rewardVisual'),'::before').content}})})();</script></body></html>`;}
function run(bin,width,height){const file=path.join(process.cwd(),`.v174-current-ui-browser-${width}.html`);fs.writeFileSync(file,fixture(width,height));try{const result=spawnSync(bin,["--headless=new","--no-sandbox","--disable-gpu","--disable-dev-shm-usage","--allow-file-access-from-files","--force-device-scale-factor=1",`--window-size=${width},${height}`,"--dump-dom","file://"+file.replace(/\\/g,"/")],{encoding:"utf8",timeout:30000,maxBuffer:12*1024*1024});assert.equal(result.status,0,result.stderr);const match=result.stdout.match(/<pre id="result">([\s\S]*?)<\/pre>/);assert.ok(match&&match[1],"browser QA result is empty");return JSON.parse(decode(match[1]));}finally{try{fs.unlinkSync(file)}catch(_){}}}
function verify(data,width){assert.equal(data.labels.normal,"13px");assert.equal(data.labels.relic,data.labels.normal,`${width}px relic label differs`);assert.equal(data.labels.element,data.labels.normal,`${width}px element-box label differs`);assert.equal(data.labels.relicLine,data.labels.normalLine);assert.equal(data.roster.marginTop,"4px");assert.equal(data.roster.gap,"2px");assert.ok(data.roster.charHeight<=78.5);assert.equal(data.gameplay.count,1);assert.equal(data.gameplay.page,"home");assert.ok(data.gameplay.back&&data.gameplay.back.left>data.gameplay.header.left+data.gameplay.header.width/2);assert.equal(data.hint.font,"16px");assert.match(data.hint.content,/土剋水.*水剋火.*火剋風.*風剋土/);assert.ok(data.equipment.cell.width>45,`${width}px inventory fixture cell collapsed`);assert.ok(data.equipment.art.width>=data.equipment.cell.width-8&&data.equipment.art.height>=data.equipment.cell.height-8,`${width}px equipment art does not fill its slot`);assert.ok(data.equipment.img.width>=data.equipment.art.width-8&&data.equipment.img.height>=data.equipment.art.height-8,`${width}px equipment image does not fill its art box`);assert.equal(data.equipment.fit,"contain");assert.equal(data.equipment.transform,"none");assert.equal(data.preview.icon,"none");assert.equal(data.preview.chest,"none");assert.match(data.preview.content,/裝備寶箱.*×2/);}
const bin=chrome();if(!bin){if(process.env.CI)throw new Error("CI must provide Chrome for V174 current UI browser QA");console.log("V174 current UI browser QA skipped: Chrome unavailable");}else{for(const [w,h] of [[390,844],[412,915]])verify(run(bin,w,h),w);console.log("✓ V174 current UI mobile browser QA passed at 390px and 412px");}
