"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const source=fs.readFileSync("js/49-v169-element-box-settings.js","utf8");
const css=fs.readFileSync("css/48-v169-element-box-settings.css","utf8");
const index=fs.readFileSync("index.html","utf8");
assert.match(source,/先停止元素匣，才能設定/);
assert.match(source,/writeSharedRecoveryFromForm/);
assert.match(source,/config\.hp=hpValue/);
assert.match(source,/config\.sp=spValue/);
assert.match(source,/config\.returnToCityWhenEmpty=returnValue/);
assert.match(source,/switchAutoSettingsCharacter=function\(initializing\)/);
assert.match(source,/elementBoxIsActive\(\)&&initializing!==true/);
assert.match(source,/field\.disabled=false/);
assert.match(source,/field\.setAttribute\("aria-disabled",active\?"true":"false"\)/);
assert.match(source,/bindLockedInteractionGuard/);
assert.match(source,/LOCKED_SETTING_SELECTOR/);
assert.match(source,/target\.closest\("#"\+STOP_BUTTON_ID\)/);
assert.match(source,/primary\.disabled=active/);
assert.doesNotMatch(source,/afterOpen[\s\S]*setTimeout\(notifyLocked/);
assert.match(index,/v17342-element-box-shared/);
assert.match(index,/共用設定/);
assert.match(index,/三名角色共用/);
assert.match(css,/v17342-element-box-lock-notice/);
assert.match(css,/v17342-settings-locked/);
assert.match(css,/overflow:hidden !important/);
console.log("v169 / V173.42 shared Element Box settings checks passed");
