"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const qol=fs.readFileSync("js/53-v173.50-inventory-qol.js","utf8");
const equipment=fs.readFileSync("js/equipment-progression.js","utf8");
const loader=fs.readFileSync("js/20-anonymous-20.js","utf8");
const ui=fs.readFileSync("js/51-v169-rpg-ui.js","utf8");
const index=fs.readFileSync("index.html","utf8");
assert.match(qol,/const finish=function\(\)\{[\s\S]*?window\.__v17351QaReady=true;[\s\S]*?v17351:qa-ready/);
assert.match(qol,/existing\.dataset\.loaded==="1"/);
assert.match(qol,/existing\.addEventListener\("load"/);
assert.match(qol,/script\.dataset\.loaded="1"/);
for(const name of ["54-v173.51-battle-qa.js","55-v173.51-inventory-qa.js","56-v173.51-shop-qa.js","57-v173.51-quest-qa.js"]){assert.ok(qol.includes(name+"?v=173.62"));}
assert.doesNotMatch(equipment,/Date\.now\(\)-startedAt>5000/);
assert.doesNotMatch(equipment,/V173\.51 功能載入逾時/);
assert.match(equipment,/document\.addEventListener\("v17351:qa-ready",onQaReady,\{once:true\}\)/);
assert.match(equipment,/30000/);
assert.match(loader,/const V_ASSET_VERSION="173\.62"/);
assert.match(loader,/dataset\.runtimeReady="173\.62"/);
assert.match(ui,/equipment-progression\.js\?v=173\.62/);
assert.match(index,/<title>四象江湖傳 V173\.62<\/title>/);
console.log("✓ V173.62 explicit QA readiness without false 5s timeout");
