"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const loader=fs.readFileSync("js/20-anonymous-20.js","utf8");
const startup=fs.readFileSync("js/52-v173.20-startup-loader.js","utf8");
const ui=fs.readFileSync("js/51-v169-rpg-ui.js","utf8");
const equipment=fs.readFileSync("js/equipment-progression.js","utf8");
const qol=fs.readFileSync("js/53-v173.50-inventory-qol.js","utf8");
const index=fs.readFileSync("index.html","utf8");
assert.match(loader,/TOTAL_RUNTIME_MODULES=32/);
assert.match(loader,/__v173ReportRuntimeProgress\(runtime\.id,runtime\.src\)/);
assert.match(loader,/dispatch\("v173:runtime-ready"/);
assert.match(loader,/dispatch\("v173:runtime-failed"/);
assert.doesNotMatch(loader,/正在同步最新遊戲系統/);
assert.doesNotMatch(loader,/v17347RuntimeGateStatus/);
assert.match(startup,/進度 0~90% 直接來自實際 runtime 模組 load 事件/);
assert.match(startup,/runtimeReady/);
assert.match(startup,/totalDuration/);
assert.match(ui,/equipment-progression\.js\?v=173\.62/);
assert.match(ui,/__v173ReportRuntimeProgress\("equipment-progression-runtime"/);
assert.match(equipment,/53-v173\.50-inventory-qol\.js\?v=173\.62/);
assert.match(equipment,/__v173ReportRuntimeProgress\("v17350-inventory-qol-runtime"/);
assert.match(qol,/54-v173\.51-battle-qa\.js\?v=173\.62/);
assert.match(qol,/57-v173\.51-quest-qa\.js\?v=173\.62/);
assert.match(qol,/__v173ReportRuntimeProgress\(pair\[0\],pair\[1\]\)/);
assert.match(index,/<title>四象江湖傳 V173\.62<\/title>/);
console.log("✓ V173.62 real startup progress integration");
