"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const synthesis=fs.readFileSync("js/36-v141-content-systems.js","utf8");
const equipment=fs.readFileSync("js/equipment-progression.js","utf8");
const css=fs.readFileSync("css/38-v141-system-expansion.css","utf8");
const loader=fs.readFileSync("js/20-anonymous-20.js","utf8");
const index=fs.readFileSync("index.html","utf8");

assert.match(synthesis,/reforgeMaterialTier:"low",lockedReforgeKeys:\[\]/);
assert.match(synthesis,/function reforgeMaterialCost\(lockCount\)/);
assert.match(synthesis,/return locks===0\?50:\(locks===1\?100:150\)/);
assert.match(synthesis,/function reforgeSlotCount\(item\)/);
assert.match(synthesis,/return !!\(item&&item\.v17351Locked!==true&&reforgeSlotCount\(item\)>0\)/);
assert.match(synthesis,/v141SelectReforgeMaterialTier/);
assert.match(synthesis,/v141ToggleReforgeLock/);
assert.match(synthesis,/candidate&&candidate\.blueprintSlot&&candidate\.tierKey===tier,cost/);
assert.match(synthesis,/v132ConsumeStackItem\(info\.ore\.id,cost\)/);
assert.match(synthesis,/stats:rollReforgeAffixes\(item,tier,locks\)/);
assert.match(synthesis,/item\.reforgeStats=Object\.assign\(\{\},pending\.stats\)/);
assert.match(synthesis,/item\.reforgeUsed=0/);
assert.doesNotMatch(synthesis,/const tier=inferTier\(item\);[\s\S]{0,500}v141StartReforge/);
assert.match(synthesis,/裝備品質不限制材料階級/);
assert.match(synthesis,/未鎖定 50 張設計圖＋50 礦石/);
assert.match(synthesis,/鎖 1 條各 100/);
assert.match(synthesis,/鎖 2 條各 150/);
assert.match(equipment,/return Math\.max\(explicit,existing\)/);
assert.doesNotMatch(equipment,/merged\[key\]=/);
assert.doesNotMatch(equipment,/item\.reforgeUsed=Math\.min/);
assert.match(css,/V173\.60 — FREE-MATERIAL REFORGE UI/);
assert.match(css,/\.v17358-reforge-tiers/);
assert.match(css,/\.v17358-affix-lock\.locked/);
assert.match(loader,/const V_ASSET_VERSION="173\.60"/);
assert.match(index,/<title>四象江湖傳 V173\.60<\/title>/);
console.log("✓ V173.60 unlimited free-material reforge redesign");
