"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const shop=fs.readFileSync("js/56-v173.51-shop-qa.js","utf8");
const equipment=fs.readFileSync("js/equipment-progression.js","utf8");
const css=fs.readFileSync("css/53-v173.51-qa.css","utf8");
const loader=fs.readFileSync("js/20-anonymous-20.js","utf8")+fs.readFileSync("scripts/build-production.mjs","utf8");
const index=fs.readFileSync("index.html","utf8");
const canonicalCss=fs.readFileSync("css/49-v169-rpg-ui.css","utf8");
assert.match(shop,/runtime retired/);
assert.doesNotMatch(shop,/MutationObserver|setInterval|setTimeout|innerHTML/);
assert.match(equipment,/function replaceEquipmentShop/);
assert.match(equipment,/v17345-equipment-wallet/);
assert.match(equipment,/v17345-equipment-grid/);
assert.match(equipment,/v17345-equipment-refresh/);
assert.ok(!css.includes(".v17351-shop-card{display:grid!important;grid-template-columns:88px"));
assert.ok(css.includes(".v17346-shop-card.purchased .v17346-shop-buy.v17351-purchased-buy"));
assert.doesNotMatch(css,/\.v17345-equipment-shop\{grid-template-rows:minmax\(0,1fr\) 64px!important/);
assert.doesNotMatch(css,/\.v17345-equipment-refresh\{height:64px!important/);
assert.match(canonicalCss,/v17345-equipment-shop[\s\S]*grid-template-rows:32px minmax\(0,1fr\) 58px\s*!important/);
assert.match(canonicalCss,/v17346-shop-card \.v17346-gear-art\{[\s\S]*overflow:hidden !important[\s\S]*box-sizing:border-box !important/);
assert.match(canonicalCss,/v17346-gear-art\s*>\s*\.v169-item-art\{[\s\S]*max-width:100% !important[\s\S]*max-height:100% !important[\s\S]*overflow:hidden !important/);
assert.match(canonicalCss,/v17346-gear-art\s*>\s*\.v169-item-art\s*>\s*(?:img|svg)\{[\s\S]*object-fit:contain !important/);
assert.match(loader,/const V_ASSET_VERSION="173\\.70"/);
assert.match(index,/<title>四象江湖傳 V173\.69<\/title>/);
console.log("✓ V173.62 restores premium equipment shop layout and click preview");
