const assert=require("assert");
const fs=require("fs");
const releaseMeta=JSON.parse(fs.readFileSync("release/release.json","utf8"));
const read=p=>fs.readFileSync(p,"utf8");
const dungeon=read("js/42-v148-combat-dungeon-fixes.js");
const legacy=read("js/27-v132-content-expansion.js");
const economy=read("js/28-v133-economy-rebalance.js");
const main=read("js/00-main.js");
const water=read("js/60-v173.64-skill-progression-rebalance.js");
const index=read("index.html");
const loader=read("js/20-anonymous-20.js")+read("scripts/build-production.mjs");
const agents=read("AGENTS.md");
assert.match(dungeon,/material:\{title:"材料副本",requirement:"任一角色達到10級"/);
assert.match(dungeon,/gold:\{title:"金幣副本",requirement:"任一角色達到10級"/);
assert.match(dungeon,/function hasLevel10Character\(\)/);
assert.doesNotMatch(dungeon,/請指定1名角色領取/);
assert.match(dungeon,/sharedExp=Math\.max\(0,numeric\(sharedExp\)\+granted\)/);
assert.match(legacy,/function hasLevel10CharacterForDailyDungeon\(\)/);
assert.doesNotMatch(legacy,/至少兩名角色都達到20級才能開啟/);
assert.doesNotMatch(economy,/grantFastStartToAdditionalCharacter/);
assert.doesNotMatch(economy,/character\.level=10/);
assert.match(main,/function buildAdditionalCharacter[\s\S]*?level:1,[\s\S]*?exp:0,/);
assert.match(water,/floodBeast:\{learnLevel:7,learnCost:6,progressionGroup:"magic"/);
assert.match(water,/floodBeast:\{baseDamage:105,damagePerLevel:21,spCost:35,targetType:"single",requires:\["waterBall"\]/);
assert.match(main,/const learnCost=eligibility\.learnCost/);
assert.match(main,/getSkillLearnEligibilityForUi\([\s\S]*?if\(!eligibility\.allowed\)/);
assert.match(main,/owner\.skillPoints=availablePoints-learnCost/);
assert.match(water,/applyFinalProgressionData\(\);/);
assert.match(water,/if\(typeof renderSkillLoadout==="function"\)\{ renderSkillLoadout\(\); \}/);
assert.ok(index.includes("<title>四象江湖傳 V"+releaseMeta.version+"</title>"));
assert.ok(index.includes('aria-label="目前版本 V'+releaseMeta.version+'"'));
assert.ok(index.includes(">V"+releaseMeta.version+"</div>"));
assert.equal((loader.match(/const V_ASSET_VERSION="([^"]+)"/)||[])[1],releaseMeta.cacheVersion);
assert.match(agents,/https:\/\/four-symbols-dev\.pages\.dev/);
console.log("V173.50 maintenance regression checks passed");
