const assert=require("assert");
const fs=require("fs");
const read=p=>fs.readFileSync(p,"utf8");
const dungeon=read("js/42-v148-combat-dungeon-fixes.js");
const legacy=read("js/27-v132-content-expansion.js");
const economy=read("js/28-v133-economy-rebalance.js");
const main=read("js/00-main.js");
const water=read("js/50-v169-water-skill-rules.js");
const index=read("index.html");
const loader=read("js/20-anonymous-20.js");
const agents=read("AGENTS.md");
assert.match(dungeon,/material:\{title:"材料副本",requirement:"任一角色達到10級"/);
assert.match(dungeon,/gold:\{title:"金幣副本",requirement:"任一角色達到10級"/);
assert.match(dungeon,/function hasLevel10Character\(\)/);
assert.doesNotMatch(dungeon,/請指定1名角色領取/);
assert.match(dungeon,/sharedExp=Math\.max\(0,numeric\(sharedExp\)\+granted\)/);
assert.match(legacy,/function hasLevel10CharacterForDailyDungeon\(\)/);
assert.doesNotMatch(legacy,/至少兩名角色都達到20級才能開啟/);
assert.doesNotMatch(economy,/grantFastStartToAdditionalCharacter/);
assert.doesNotMatch(economy,/character\.level=10/);
assert.match(main,/function buildAdditionalCharacter[\s\S]*?level:1,[\s\S]*?exp:0,/);
assert.match(water,/floodBeast:\{[\s\S]*?learnCost:15[\s\S]*?requires:\["waterBall"\]/);
assert.match(main,/const learnCost=Math\.max\(0,Number\(skill\.learnCost\)\|\|0\)/);
assert.match(main,/owner\.skillPoints=availablePoints-learnCost/);
assert.match(water,/applyFinalSkillData\(\);[\s\S]*?renderSkillLoadout\(\)/);
assert.match(index,/<title>四象江湖傳 V173\.53<\/title>/);
assert.match(index,/aria-label="目前版本 V173\.53"[\s\S]*?>V173\.53<\/div>/);
assert.match(loader,/const V_ASSET_VERSION="173\.53"/);
assert.match(agents,/https:\/\/four-symbols-dev\.pages\.dev/);
console.log("V173.50 maintenance regression checks passed");
