const assert=require("node:assert/strict");
const fs=require("node:fs");
const index=fs.readFileSync("index.html","utf8");
const app=fs.readFileSync("js/20-anonymous-20.js","utf8");
const css=fs.readFileSync("css/56-v174-critical-ui-regressions.css","utf8");
const city=fs.readFileSync("js/16-stage-v54-main-city-runtime.js","utf8");
const cityCss=fs.readFileSync("css/19-stage-v54-main-city-moderate-native-scale.css","utf8");
const relic=fs.readFileSync("js/60-team-relic-system.js","utf8");
const relicCss=fs.readFileSync("css/55-team-relic-system.css","utf8");
assert.match(index,/team-relic-home-entry[^>]*data-feature="relic"/);
assert.match(index,/team-element-box-home-entry[^>]*data-feature="gameplay-core"/);
assert.match(index,/aria-label="主城常駐功能"/);
assert.doesNotMatch(app,/ensure\("relic","home-utilities"\)/);
assert.match(app,/four-symbols:startup-ready[\s\S]{0,500}\.idle\(/);
assert.match(city,/FourSymbolsHomeRelicSummary/);
assert.match(city,/ensureHomeRosterShell/);
assert.match(city,/HOME_RELIC_SUMMARY_CATALOG/);
assert.match(cityCss,/team-relic-loadout-slot/);
assert.doesNotMatch(relic,/createElement\("div"\)[\s\S]{0,160}team-relic-loadout-slot/);
assert.doesNotMatch(relicCss,/team-relic-loadout-slot/);
assert.match(css,/Main-city persistent utility shell/);
assert.match(css,/\.team-relic-home-tools\{[\s\S]*grid-template-columns:repeat\(2,80px\)/);
console.log("V173.65 dev-deploy home utility regression checks passed.");
