"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"..");
const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const html=read("index.html");
const mainCss=read("css/00-main.css");
const dailyCss=read("css/43-v148-combat-dungeon-fixes.css");
const oldSkillCss=read("css/38-v141-system-expansion.css");
const ui=read("js/35-v141-ui-battle.js");
const core=read("js/34-v141-core-systems.js");
const quest=read("js/00-main.js");
const questQa=read("js/57-v173.51-quest-qa.js");
const daily=read("js/42-v148-combat-dungeon-fixes.js");
const content=read("js/27-v132-content-expansion.js");
const equipment=read("js/equipment-progression.js");
const loader=read("js/20-anonymous-20.js");
assert.ok(fs.existsSync(path.join(root,"assets/items/materials/ore.png")));
assert.ok(fs.existsSync(path.join(root,"assets/items/chests/dungeon-chest.png")));
assert.match(content,/assets\/items\/materials\/ore\.png/);
assert.match(content,/assets\/items\/chests\/dungeon-chest\.png/);
assert.match(content,/syncV17361ItemArt/);
assert.match(mainCss,/img\[src\*="map-return\.png"\][\s\S]*background:#050505/);
assert.match(html,/id="quickPowerSavingToggle"/);
assert.match(core,/navigator\.wakeLock\.request\("screen"\)/);
assert.match(core,/V17361_POWER_SAVE_KEY/);
assert.match(core,/master\.gain\.value=0\.30/);
assert.doesNotMatch(ui,/v141-once-/);
assert.doesNotMatch(oldSkillCss,/v141HealFlash|v141ReviveFlash|v141TalismanFlash|v141-once-/);
assert.match(daily,/v17361DailyRewardVisual/);
assert.match(dailyCss,/v17361-reward-visual/);
assert.doesNotMatch(equipment,/⬜|🟦|🟪|🟧/);
assert.match(equipment,/rarity-white/);
assert.match(quest,/v17361ClaimAllDailyQuests/);
assert.match(quest,/v17361ClaimAllCommissionQuests/);
assert.match(quest,/v17361RefreshOpenQuestPage/);
assert.match(core,/v17361RefreshOpenQuestPage/);
assert.match(questQa,/__v17361BulkQuestClaim/);
assert.match(questQa,/v17351ClaimAllAchievements/);
assert.ok(loader.includes('const V_ASSET_VERSION="173.61";'));
assert.ok(html.includes('<title>四象江湖傳 V173.61</title>'));
console.log("✓ V173.61 current request integration");
