"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const v131=fs.readFileSync("js/25-v131-fix-batch.js","utf8");
const v141=fs.readFileSync("js/35-v141-ui-battle.js","utf8");
const abyss=fs.readFileSync("js/36-v141-content-systems.js","utf8");
const recovery=fs.readFileSync("js/45-v154-dev-fixes.js","utf8");
const settings=fs.readFileSync("js/49-v169-element-box-settings.js","utf8");
const index=fs.readFileSync("index.html","utf8");
const baseCss=fs.readFileSync("css/00-main.css","utf8");
const abyssCss=fs.readFileSync("css/46-v154-dev-fixes.css","utf8");
const core=fs.readFileSync("js/00-main.js","utf8");
assert.match(v141,/v17342UseInventoryPotion/);
assert.match(v141,/getBackpackCharacter\(inventoryCharacterIndex\)/);
assert.match(settings,/先停止元素匣，才能設定/);
assert.match(index,/v17342-element-box-shared/);
assert.match(recovery,/setInterval\(\(\)=>\{[\s\S]*isElementBoxRecoveryActive/);
assert.match(recovery,/v17342PendingBattleNotices/);
assert.match(core,/pendingElementBoxNotices/);
assert.match(abyss,/v17342-abyss-battle-info/);
assert.match(abyssCss,/aspect-ratio:9\/16/);
assert.match(v141,/hasExpLevelUp/);
assert.doesNotMatch(index,/home-utility-actions/);
assert.match(baseCss,/grid-template-rows:repeat\(4,82px\)/);
assert.match(v131,/V17342_GLOBAL_EXP_REWARD_MULTIPLIER=3/);
assert.match(v131,/V17342_GLOBAL_GOLD_REWARD_MULTIPLIER=5/);
assert.match(v131,/getBeginnerForestMonsterExpUnit/);
assert.match(v131,/beginnerMonsterUnits/);
console.log("✓ V173.42 player flow / economy / Element Box regression passed");
