"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=p=>fs.readFileSync(p,"utf8");
const css=read("css/56-v174-critical-ui-regressions.css");
const touch=read("js/01-stage-v8-touch-lock.js");
const boss=read("css/gameplay-boss-tower.css");
const skill=read("js/60-v173.64-skill-progression-rebalance.js");
const exp=read("js/28-v133-economy-rebalance.js");
const slots=read("js/25-v131-fix-batch.js");
const slotCss=read("css/31-v131-fix-batch.css");
assert.match(css,/#creationPage \.creation-role-card\{[\s\S]*overflow-y:auto !important;[\s\S]*touch-action:pan-y !important;/);
assert.match(touch,/\.creation-page-scroll, \.creation-role-card, \.inventory-grid-scroll/);
assert.match(css,/#v146HomeRoster \.v146-home-resource\{[\s\S]*height:14px !important;/);
assert.match(css,/#v146HomeRoster \.v146-home-resource strong\{[\s\S]*font-size:11px !important;/);
assert.match(boss,/gameplay-boss-card\[data-rank="boss"\]\{[\s\S]*aspect-ratio:4 \/ 3;/);
assert.match(boss,/\.boss-mechanism-card\{[\s\S]*aspect-ratio:4 \/ 3;/);
assert.match(boss,/max-height:840px[\s\S]*--gameplay-boss-card-width[\s\S]*--gameplay-mechanism-card-width/);
assert.doesNotMatch(skill,/function addProgressionHint|addProgressionHint\(/);
assert.match(skill,/renderSkillDetailProgression[\s\S]*最低學習等級[\s\S]*前置技能/);
assert.match(exp,/v131ConfirmExpPreview=async function/);
assert.match(exp,/await window\.rpgConfirm\(confirmMessage,[\s\S]*title:"確認經驗池升級"/);
assert.doesNotMatch(exp,/\b(?:window\.)?confirm\s*\(/,"EXP guard must not bypass the serial RPG dialog queue");
assert.match(exp,/if\(!approved\)\{[\s\S]*return false;[\s\S]*sharedExp=Number\.MAX_SAFE_INTEGER/);
assert.ok(slots.includes("querySelectorAll('[onclick*=\"openCharacterCreation\"]')"),"current character creation slot selector missing");
assert.match(slots,/cardsBySlot\.get\(slotNumber\)/);
assert.match(slotCss,/\.v131-unlock-dot\{[\s\S]*right:4px;[\s\S]*top:4px;[\s\S]*z-index:8;/);
console.log("✓ V174 mobile UI + EXP guard source contracts passed");