"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const battle=fs.readFileSync("js/54-v173.51-battle-qa.js","utf8");
const fixedSlotCss=fs.readFileSync("css/fixed-slot-battlefield-rendering-v2.css","utf8");
const css=fs.readFileSync("css/gameplay-boss-tower.css","utf8");
const boss=fs.readFileSync("js/gameplay-boss-tower-system.js","utf8");
const relic=fs.readFileSync("js/relic-progression-drop-system.js","utf8");
assert.doesNotMatch(battle,/battle-player\.v174-cardless-unit>\.v174-battle-art\{[\s\S]*?inset:/,"V173.51 must not own player artwork bounds");
assert.doesNotMatch(battle,/battle-monster\.v174-cardless-unit>\.v174-battle-art\{[\s\S]*?inset:/,"V173.51 must not own enemy artwork bounds");
assert.match(fixedSlotCss,/\.v-fixed-battle-slot > \.battle-monster > \.v174-battle-art,[\s\S]*\.v-fixed-ally-slot > \.battle-player > \.v174-battle-art\{[\s\S]*?background-size:contain !important;/,"fixed Slot CSS must own no-crop artwork geometry");
assert.doesNotMatch(fixedSlotCss,/\.v174-battle-art\{[^}]*?background-size:cover !important;/s,"enemy combat art must not regress to cover cropping");
assert.doesNotMatch(battle,/battle-player\.v174-cardless-unit\{[^}]*?(?:width|max-width|min-height|height):/s,"art sizing must not resize player combat slots");
assert.doesNotMatch(battle,/battle-monster\.v174-cardless-unit\{[^}]*?(?:width|max-width|min-height|height):/s,"art enlargement must not resize enemy combat slots");
assert.doesNotMatch(battle,/battle-player\.v174-cardless-unit>\.hp-bar\{[\s\S]*?bottom:/,"V173.51 must not own player HP position");
assert.doesNotMatch(battle,/battle-player\.v174-cardless-unit>\.sp-bar\{[\s\S]*?bottom:/,"V173.51 must not own player SP position");
assert.match(fixedSlotCss,/\.v-fixed-enemy-slot \.monster-hp,[\s\S]*\.v-fixed-ally-slot \.hp-bar\{bottom:11px !important;\}/,"fixed Slot CSS must own HP anchor");
assert.match(fixedSlotCss,/\.v-fixed-enemy-slot \.monster-sp,[\s\S]*\.v-fixed-ally-slot \.sp-bar\{bottom:1px !important;\}/,"fixed Slot CSS must own SP anchor");
assert.match(css,/\.gameplay-hub-grid\{[\s\S]*?display:flex;[\s\S]*?flex-direction:column;/);
assert.match(css,/\.gameplay-mode-card\{[\s\S]*?flex:0 0 auto;[\s\S]*?aspect-ratio:16 \/ 9;/);
const detail=boss.slice(boss.indexOf("function bossDetailMarkup"),boss.indexOf("function renderBossPage"));
assert.ok(detail.indexOf("gameplay-primary-action")<detail.indexOf("boss-detail-grid"),"BOSS challenge action must render above recommended-party grid");
assert.match(relic,/grid\.insertBefore\(section,grid\.firstElementChild\)/,"relic preview must be first detail section");
console.log("V174.1 battle/gameplay layout ordering regression checks passed");
