"use strict";

const assert=require("node:assert/strict");
const crypto=require("node:crypto");
const fs=require("node:fs");
const {spawnSync}=require("node:child_process");
const read=file=>fs.readFileSync(file,"utf8");
const inventoryCss=read("css/38-v141-system-expansion.css");
const hintCss=read("css/56-v174-critical-ui-regressions.css");
const rosterCss=read("css/42-v146-system-polish.css");
const relicCss=read("css/55-team-relic-system.css");
const rewardCss=read("css/33-v132-content-expansion.css");
const equipmentJs=read("js/equipment-progression.js");
const html=read("index.html");
const manifest=JSON.parse(read("asset-manifest.json"));
assert.match(inventoryCss,/#game-stage #inventoryPage \.v169-item-art\.v169-equipment-art\{[\s\S]*place-items:center;[\s\S]*object-fit:contain;/);
assert.doesNotMatch(inventoryCss,/#game-stage #inventoryPage \.v169-item-art\.v169-equipment-art\{[^}]*!important/s);
assert.match(hintCss,/#allElementSkillPreviewModal \.skill-preview-body::before\{[\s\S]*font-size:16px;[\s\S]*line-height:1\.45;/);
assert.doesNotMatch(hintCss,/body #game-stage #allElementSkillPreviewModal/);
assert.match(rosterCss,/@media \(max-height:920px\)[\s\S]*v146-home-roster[\s\S]*margin-top:4px;[\s\S]*v146-home-character[\s\S]*min-height:78px;/);
assert.match(relicCss,/team-relic-home-tools \.home-card-label\{[^}]*font-size:13px;[^}]*line-height:18px;[^}]*font-weight:900;/);
assert.match(relicCss,/home-relic-v174\.eed14e806044\.webp/);
assert.match(rewardCss,/\.v132-reward-modal \.v132-reward-modal-inner\.v17363-text-reward-preview/);
assert.doesNotMatch(rewardCss,/#game-stage \.v17363-text-reward-preview/);
assert.match(rewardCss,/width:min\(calc\(100vw - 32px\),392px\) !important;[\s\S]*max-width:calc\(100vw - 32px\) !important;/);
const start=equipmentJs.indexOf("window.v17346ShowEquipmentDungeonPreview"),end=equipmentJs.indexOf("if(typeof renderDungeonTabContent",start),preview=equipmentJs.slice(start,end);
assert.match(preview,/equipmentChestOddsText/);assert.match(preview,/v17363-text-reward-preview/);assert.match(preview,/裝備品階機率/);
assert.doesNotMatch(preview,/previewAssets|v17361-reward-icon|<img/);
assert.equal((html.match(/class="gameplay-back-button v174-gameplay-home-back"/g)||[]).length,1);
assert.match(html,/v174-gameplay-home-back" onclick="showPage\('home'\)" aria-label="返回主城"/);
assert.equal(fs.existsSync("css/57-v174-current-ui-fixes.css"),false);
assert.equal(fs.existsSync("js/62-v174-current-ui-fixes.js"),false);
assert.equal(manifest.featureManifest.bundles["app-shell"].scripts.length,1);
assert.equal(manifest.featureManifest.bundles["app-shell"].styles.length,1);
assert.doesNotMatch(read("asset-manifest.json"),/app-ui-fixes/);
assert.equal(read("asset-manifest.json"),read("build/asset-manifest.json"));
const relic=fs.readFileSync("assets/ui/home-relic-v174.eed14e806044.webp");
assert.equal(relic.subarray(0,4).toString("ascii"),"RIFF");assert.equal(relic.subarray(8,12).toString("ascii"),"WEBP");
assert.equal(crypto.createHash("sha256").update(relic).digest("hex").slice(0,12),"eed14e806044");
function webpDimensions(buffer){let offset=12;while(offset+8<=buffer.length){const kind=buffer.toString("ascii",offset,offset+4),size=buffer.readUInt32LE(offset+4),data=offset+8;if(kind==="VP8X")return [1+buffer.readUIntLE(data+4,3),1+buffer.readUIntLE(data+7,3)];if(kind==="VP8 "){const marker=buffer.indexOf(Buffer.from([0x9d,0x01,0x2a]),data);if(marker>=data&&marker<data+size)return [buffer.readUInt16LE(marker+3)&0x3fff,buffer.readUInt16LE(marker+5)&0x3fff]}if(kind==="VP8L"){const bits=buffer.readUInt32LE(data+1);return [1+(bits&0x3fff),1+((bits>>14)&0x3fff)]}offset=data+size+(size%2)}throw new Error("Unsupported WebP layout")}
assert.deepEqual(webpDimensions(relic),[144,144]);
const buildCheck=spawnSync(process.execPath,["scripts/build-production.mjs","--check"],{encoding:"utf8"});
assert.equal(buildCheck.status,0,buildCheck.stderr||buildCheck.stdout||"production build check failed");
console.log("✓ V174 current UI owner-convergence checks passed");
