"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const {spawnSync}=require("node:child_process");
function chrome(){ for(const n of ["google-chrome","google-chrome-stable","chromium","chromium-browser"]){ const p=spawnSync("bash",["-lc",`command -v ${n}`],{encoding:"utf8"}); if(p.status===0&&p.stdout.trim()) return p.stdout.trim(); } return ""; }
function decode(v){return v.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'");}
const c=chrome(); if(!c){ if(process.env.CI) throw new Error("Chrome required"); console.log("mobile UI guards browser QA skipped"); process.exit(0); }
const fixture=path.join(process.cwd(),".v174-mobile-ui-guards-browser.html");
const filler=Array.from({length:18},(_,i)=>`<p>元素說明第 ${i+1} 行：治療、控場與隊伍回復。</p>`).join("");
fs.writeFileSync(fixture,`<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="css/42-v146-system-polish.css"><link rel="stylesheet" href="css/56-v174-critical-ui-regressions.css"><style>html,body{margin:0;width:1080px;height:1920px;background:#050505}#game-stage{width:396px;height:900px}#homePage{display:block!important;width:396px}.probe-choice{display:flex!important;flex-direction:column!important;width:480px!important;height:360px!important}.probe-role{height:auto!important}.probe-role p{margin:8px 0}</style></head><body><div id="game-stage"><div id="homePage"><div id="v146HomeRoster" class="v146-home-roster"><header>冒險隊伍</header><div class="v146-home-character"><div class="v146-home-avatar"></div><div class="v146-home-character-main"><div><b>火測試</b><span>Lv.30</span></div><div class="v146-home-resource"><i></i><strong>HP 2470 / 2470</strong></div><div class="v146-home-resource sp"><i></i><strong>SP 340 / 340</strong></div></div></div></div></div></div><div id="creationPage"><div class="creation-choice-panel probe-choice"><div style="flex:0 0 120px">性別／元素選擇</div><div class="creation-role-card probe-role">${filler}</div></div></div><pre id="result"></pre><script>var bar=document.querySelector('.v146-home-resource'),text=bar.querySelector('strong'),role=document.querySelector('.creation-role-card');var before=role.scrollTop;role.scrollTop=role.scrollHeight;var s=getComputedStyle(role);document.getElementById('result').textContent=JSON.stringify({barHeight:getComputedStyle(bar).height,font:getComputedStyle(text).fontSize,textOverflow:text.scrollWidth>text.clientWidth+1,roleOverflow:s.overflowY,touch:s.touchAction,scrollHeight:role.scrollHeight,clientHeight:role.clientHeight,before:before,after:role.scrollTop});</script></body></html>`,"utf8");
try{ const r=spawnSync(c,["--headless=new","--no-sandbox","--disable-gpu","--allow-file-access-from-files","--window-size=1100,1950","--dump-dom","file://"+fixture.replace(/\\/g,"/")],{encoding:"utf8",timeout:30000,maxBuffer:8*1024*1024}); assert.equal(r.status,0,r.stderr); const m=r.stdout.match(/<pre id="result">([\s\S]*?)<\/pre>/); assert.ok(m); const d=JSON.parse(decode(m[1])); assert.equal(d.barHeight,"14px"); assert.equal(d.font,"11px"); assert.equal(d.textOverflow,false,"HP/SP text still overflows the compact roster bar"); assert.match(d.roleOverflow,/auto|scroll/); assert.equal(d.touch,"pan-y"); assert.ok(d.scrollHeight>d.clientHeight&&d.after>d.before,"creation element explanation is not actually scrollable"); console.log("✓ V174 home HUD + creation scroll browser QA passed",d); } finally { try{fs.unlinkSync(fixture)}catch(_){} }
